apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
        - name: todo-ui
          image: todoappacr2ly.azurecr.io/todo-ui:latest
          ports:
            - containerPort: 8080
