apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-delete-task
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agentic-delete-task
  template:
    metadata:
      labels:
        app: agentic-delete-task
    spec:
      containers:
      - name: agentic-delete-task
        env:
          - name: CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: agentic-sql-secret
                key: CONNECTION_STRING
        image: agenticdevopsacr.azurecr.io/delete-tasks:latest
        ports:
        - containerPort: 8000
