apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-incident-resolve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentic-incident-resolve
  template:
    metadata:
      labels:
        app: agentic-incident-resolve
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: agentic-incident-resolve
          image: agenticdevopsacr.azurecr.io/incident-resolve:latest
          ports:
            - containerPort: 8000
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: agentic-sql-secret
                  key: CONNECTION_STRING
