apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels:
        app: add-task
    spec:
      containers:
      - name: add-task
        image: todoappacr.azurecr.io/add-tasks:latest
        ports:
        - containerPort: 8000
