# Azure SQL Server + Database for CloudOps incidents
# Password is generated by Terraform and stored only in Terraform state.

resource "random_password" "sql_admin" {
  length           = 24
  special          = false
  upper            = true
  lower            = true
  numeric          = true
  min_upper        = 2
  min_lower        = 2
  min_numeric      = 2
}

resource "azurerm_mssql_server" "sqlserver" {
  name                         = "agentic-devops-sql"
  resource_group_name          = azurerm_resource_group.rg.name
  location                     = azurerm_resource_group.rg.location
  version                      = "12.0"
  administrator_login          = "sqladminuser"
  administrator_login_password = random_password.sql_admin.result
}

resource "azurerm_mssql_database" "todo_db" {
  name        = "agentsql"
  server_id   = azurerm_mssql_server.sqlserver.id
  sku_name    = "S0"
  max_size_gb = 5
}

# Allow Azure-hosted workloads to reach SQL for this demo deployment.
resource "azurerm_mssql_firewall_rule" "allow_azure_services" {
  name             = "AllowAzureServices"
  server_id        = azurerm_mssql_server.sqlserver.id
  start_ip_address = "0.0.0.0"
  end_ip_address   = "0.0.0.0"
}
