apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-incident-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentic-incident-list
  template:
    metadata:
      labels:
        app: agentic-incident-list
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: agentic-incident-list
          image: agenticdevopsacr.azurecr.io/incident-list:latest
          ports:
            - containerPort: 8000
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: agentic-sql-secret
                  key: CONNECTION_STRING
