name: Deploy Backend Services to AKS

on:
    workflow_dispatch: # Manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set AKS context
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      # ---------------------- AddTaskTodoMicroservice ----------------------
      - name: Build & Push AddTaskTodoMicroservice image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/addtask-todo:latest ./backend/AddTaskTodoMicroservice
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/addtask-todo:latest

      - name: Deploy AddTaskTodoMicroservice
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./backend/AddTaskTodoMicroservice/manifests/deployment.yaml
            ./backend/AddTaskTodoMicroservice/manifests/service.yaml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/addtask-todo:latest
          imagepullsecrets: |
            acr-secret

      # ---------------------- GetTasksTodoMicroservice ----------------------
      - run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/gettasks-todo:latest ./backend/GetTasksTodoMicroservice
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/gettasks-todo:latest

      - name: Deploy GetTasksTodoMicroservice
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./backend/GetTasksTodoMicroservice/manifests/deployment.yaml
            ./backend/GetTasksTodoMicroservice/manifests/service.yaml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/gettasks-todo:latest
          imagepullsecrets: |
            acr-secret

      # ---------------------- DeleteTaskTodoMicroservice ----------------------
      - run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/deletetask-todo:latest ./backend/DeleteTaskTodoMicroservice
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/deletetask-todo:latest

      - name: Deploy DeleteTaskTodoMicroservice
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./backend/DeleteTaskTodoMicroservice/manifests/deployment.yaml
            ./backend/DeleteTaskTodoMicroservice/manifests/service.yaml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/deletetask-todo:latest
          imagepullsecrets: |
            acr-secret
