name: Deploy to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: prodacrdemo                # e.g. myregistry
  ACR_LOGIN_SERVER: prodacrdemo.azurecr.io
  RESOURCE_GROUP: prod-aks-rg
  AKS_CLUSTER: prod-aks-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Azure login with federated credentials
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 2. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 3. Build and push all backend images
      - name: Build and push backend images
        run: |
          az acr login --name $ACR_NAME

          # Build all images
          docker build -t $ACR_LOGIN_SERVER/get-tasks:latest ./backend/GetTasksTodoMicroservice
          docker build -t $ACR_LOGIN_SERVER/add-tasks:latest ./backend/AddTasksTodoMicroservice
          docker build -t $ACR_LOGIN_SERVER/delete-tasks:latest ./backend/DeleteTasksTodoMicroservice
          
          # Push all images
          docker push $ACR_LOGIN_SERVER/get-tasks:latest
          docker push $ACR_LOGIN_SERVER/add-tasks:latest
          docker push $ACR_LOGIN_SERVER/delete-tasks:latest

      # 4. Get AKS credentials
      - name: Get AKS credentials
        run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER --overwrite-existing

      # 5. Deploy to AKS
      - name: Deploy manifests
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            backend/GetTasksTodoMicroservice/manifests/deployment.yaml
            backend/GetTasksTodoMicroservice/manifests/service.yaml
            backend/AddTasksTodoMicroservice/manifests/deployment.yaml
            backend/AddTasksTodoMicroservice/manifests/service.yaml
            backend/DeleteTasksTodoMicroservice/manifests/deployment.yaml
            backend/DeleteTasksTodoMicroservice/manifests/service.yaml
          images: |
            ${{ env.ACR_LOGIN_SERVER }}/get-tasks:latest
            ${{ env.ACR_LOGIN_SERVER }}/add-tasks:latest
            ${{ env.ACR_LOGIN_SERVER }}/delete-tasks:latest
