name: Deploy Backends Sequentially

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-addtask:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy AddTaskTodoMicroservice
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./AddTaskTodoMicroservice/manifests/deployment.yaml
            ./AddTaskTodoMicroservice/manifests/service.yaml
          images: prodacrdemo.azurecr.io/addtask:${{ github.sha }}
          namespace: default

      - name: Wait for AddTask to be Ready
        run: kubectl rollout status deployment/addtasktodomicroservice -n default

  deploy-gettask:
    runs-on: ubuntu-latest
    needs: deploy-addtask
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy GetTasksTodoMicroservice
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./GetTasksTodoMicroservice/manifests/deployment.yaml
            ./GetTasksTodoMicroservice/manifests/service.yaml
          images: prodacrdemo.azurecr.io/gettasks:${{ github.sha }}
          namespace: default

      - name: Wait for GetTasks to be Ready
        run: kubectl rollout status deployment/gettaskstodomicroservice -n default

  deploy-deletetask:
    runs-on: ubuntu-latest
    needs: deploy-gettask
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy DeleteTasksTodoMicroservice
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./DeleteTasksTodoMicroservice/manifests/deployment.yaml
            ./DeleteTasksTodoMicroservice/manifests/service.yaml
          images: prodacrdemo.azurecr.io/deletetasks:${{ github.sha }}
          namespace: default

      - name: Wait for DeleteTasks to be Ready
        run: kubectl rollout status deployment/deletetaskstodomicroservice -n default
