name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Azure login using federated credentials
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Set AKS context
      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      # 4. Build & push Docker images to ACR
      - name: Build and Push GetTasks image
        run: |
          az acr build --registry ${{ secrets.ACR_NAME }} --image get-tasks:latest ./backend/GetTasksTodoMicroservice
      - name: Build and Push AddTasks image
        run: |
          az acr build --registry ${{ secrets.ACR_NAME }} --image add-tasks:latest ./backend/AddTasksTodoMicroservice
      - name: Build and Push DeleteTasks image
        run: |
          az acr build --registry ${{ secrets.ACR_NAME }} --image delete-tasks:latest ./backend/DeleteTasksTodoMicroservice

      # 5. Deploy to AKS
      - name: Deploy manifests
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            backend/GetTasksTodoMicroservice/manifests/deployment.yaml
            backend/GetTasksTodoMicroservice/manifests/service.yaml
            backend/AddTasksTodoMicroservice/manifests/deployment.yaml
            backend/AddTasksTodoMicroservice/manifests/service.yaml
            backend/DeleteTasksTodoMicroservice/manifests/deployment.yaml
            backend/DeleteTasksTodoMicroservice/manifests/service.yaml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/get-tasks:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/add-tasks:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/delete-tasks:latest
          imagepullsecrets: |
            acr-secret
