name: Build and Deploy Microservices

on:
  push:
    branches:
      - main

env:
  ACR_NAME: prodacrdemo

jobs:
  build_add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build AddTasksTodoMicroservice
        run: |
          az acr build \
            --registry ${{ env.ACR_NAME }} \
            --image AddTasksTodoMicroservice:${{ github.sha }} \
            ./TODOAPP-K8S-DEPLOY/AddTasksTodoMicroservice

  build_get:
    needs: build_add
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build GetTasksTodoMicroservice
        run: |
          az acr build \
            --registry ${{ env.ACR_NAME }} \
            --image GetTasksTodoMicroservice:${{ github.sha }} \
            ./TODOAPP-K8S-DEPLOY/GetTasksTodoMicroservice

  build_delete:
    needs: build_get
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build DeleteTasksTodoMicroservice
        run: |
          az acr build \
            --registry ${{ env.ACR_NAME }} \
            --image DeleteTasksTodoMicroservice:${{ github.sha }} \
            ./TODOAPP-K8S-DEPLOY/DeleteTasksTodoMicroservice

  deploy:
    needs: build_delete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to AKS
        run: |
          # Example deploy command (replace with your own)
          kubectl apply -f ./TODOAPP-K8S-DEPLOY/k8s-manifests/
