name: Build, Push & Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Azure login
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Log in to ACR
      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # 4. Build & Push images
      - name: Build & Push get-tasks
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/get-tasks:latest ./backend/GetTasksTodoMicroservice
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/get-tasks:latest

      - name: Build & Push add-tasks
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/add-tasks:latest ./backend/AddTasksTodoMicroservice
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/add-tasks:latest

      - name: Build & Push delete-tasks
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/delete-tasks:latest ./backend/DeleteTasksTodoMicroservice
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/delete-tasks:latest

      # 5. Set AKS context
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

      # 6. Deploy to AKS
      - name: Deploy manifests
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            backend/GetTasksTodoMicroservice/manifests/deployment.yaml
            backend/GetTasksTodoMicroservice/manifests/service.yaml
            backend/AddTasksTodoMicroservice/manifests/deployment.yaml
            backend/AddTasksTodoMicroservice/manifests/service.yaml
            backend/DeleteTasksTodoMicroservice/manifests/deployment.yaml
            backend/DeleteTasksTodoMicroservice/manifests/service.yaml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/get-tasks:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/add-tasks:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/delete-tasks:latest
          imagepullsecrets: |
            acr-secret
