name: Deploy Backend Services to AKS

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for federated identity
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure Login with Federated Credentials
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Set AKS context
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      # Login to ACR
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # ---------------------- AddTaskTodoMicroservice ----------------------
      - run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/addtask-todo:latest ./backend/AddTaskTodoMicroservice
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/addtask-todo:latest

      - name: Deploy AddTaskTodoMicroservice
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./backend/AddTaskTodoMicroservice/manifests/deployment.yaml
            ./backend/AddTaskTodoMicroservice/manifests/service.yaml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/addtask-todo:latest
          imagepullsecrets: |
            acr-secret

      # ---------------------- GetTasksTodoMicroservice ----------------------
      - run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/gettasks-todo:latest ./backend/GetTasksTodoMicroservice
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/gettasks-todo:latest

      - name: Deploy GetTasksTodoMicroservice
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./backend/GetTasksTodoMicroservice/manifests/deployment.yaml
            ./backend/GetTasksTodoMicroservice/manifests/service.yaml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/gettasks-todo:latest
          imagepullsecrets: |
            acr-secret

      # ---------------------- DeleteTaskTodoMicroservice ----------------------
      - run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/deletetask-todo:latest ./backend/DeleteTaskTodoMicroservice
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/deletetask-todo:latest

      - name: Deploy DeleteTaskTodoMicroservice
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./backend/DeleteTaskTodoMicroservice/manifests/deployment.yaml
            ./backend/DeleteTaskTodoMicroservice/manifests/service.yaml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/deletetask-todo:latest
          imagepullsecrets: |
            acr-secret
