name: Deploy to AKS

on:
  workflow_dispatch: # Run manually only

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Azure using federated credentials
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Set AKS context
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      # 4. Log in to ACR (no username/password needed)
      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # 5. Build & Push all backend images to ACR
      - name: Build & Push Images
        run: |
          az acr build --registry ${{ secrets.ACR_NAME }} --image get-tasks:latest ./TODOAPP-K8S-DEPLOY/GetTasksTodoMicroservice
          az acr build --registry ${{ secrets.ACR_NAME }} --image add-tasks:latest ./TODOAPP-K8S-DEPLOY/AddTasksTodoMicroservice
          az acr build --registry ${{ secrets.ACR_NAME }} --image delete-tasks:latest ./TODOAPP-K8S-DEPLOY/DeleteTasksTodoMicroservice

      # 6. Deploy to AKS
      - name: Deploy manifests
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            TODOAPP-K8S-DEPLOY/GetTasksTodoMicroservice/manifests/deployment.yaml
            TODOAPP-K8S-DEPLOY/GetTasksTodoMicroservice/manifests/service.yaml
            TODOAPP-K8S-DEPLOY/AddTasksTodoMicroservice/manifests/deployment.yaml
            TODOAPP-K8S-DEPLOY/AddTasksTodoMicroservice/manifests/service.yaml
            TODOAPP-K8S-DEPLOY/DeleteTasksTodoMicroservice/manifests/deployment.yaml
            TODOAPP-K8S-DEPLOY/DeleteTasksTodoMicroservice/manifests/service.yaml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/get-tasks:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/add-tasks:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/delete-tasks:latest
