name: Build & Deploy get Task

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: prod-aks-rg
  AKS_CLUSTER: prod-aks-demo
  ACR_NAME: prodacrdemo
  BUILD_CONTEXT: ./backend/GetTasksTodoMicroservice
  IMAGE_NAME: update-tasks
  CONTAINER_PORT: 8080

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login with Federated Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Debug build context
        run: |
          ls -la $BUILD_CONTEXT || (echo "Path not found: $BUILD_CONTEXT" && exit 1)
          test -f "$BUILD_CONTEXT/Dockerfile" || (echo "Dockerfile not found in $BUILD_CONTEXT" && exit 1)

      - name: Build and Push image to ACR
        run: |
          az acr build --registry $ACR_NAME --image $IMAGE_NAME:latest $BUILD_CONTEXT

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl apply -f $BUILD_CONTEXT/deployment.yaml
